version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000" # Jo bhi aap ka backend port hai

  frontend:
    build: ./frontend
    ports:
      - "3000:3000" # Jo bhi aap ka frontend port hai
    depends_on:
      backend:
        condition: service_started